name = "LogarithmicNumbers"
uuid = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
authors = ["Christopher Doris"]
version = "0.4.2"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"

[compat]
julia = "1.0"
Requires = "1"

[extras]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[targets]
test = ["Distributions", "SpecialFunctions", "StatsFuns", "Test"]
